import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link href='./logo.jpeg' rel="shortcut icon"/> 
        <title>TodoApp</title>
      </head>
      <body className={inter.className}>
        <div className='max-w-3xl mx-auto px-4'>
          <Navbar />
          <div className='mt-3'>{children}</div>
        </div>
      </body>
    </html>
  )
}
